[package]
name = "state_pattern"
version = "0.1.0"
authors = ["Lars Jansøn Engvik <lars@engvik.nu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
